<?php
/**
 * Created by PhpStorm.
 * User: ducngoc
 * Date: 22/10/2016
 * Time: 14:55
 */

namespace frontend\modules\order\models;
use common\models\read\Read;

class ProductCategory extends Read
{
  public static function tableName()
  {
    return 'cms_products_category'; // TODO: Change the autogenerated stub
  }
}